# Copyright 2012 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe QuizzesController do

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # QuizzesController. Be sure to keep this updated too.
  def valid_session
    { :oauth2_token => valid_login_token }
  end

  before(:each) do
    stub_plus_discovery_document
    stub_current_user_profile
  end

  describe "GET index" do
    it "assigns all quizzes as @quizzes" do
      quiz = Factory :quiz
      get :index, {}, valid_session
      assigns(:quizzes).should eq([quiz])
    end

    it "handles when google-api-ruby-client encounters an expired access token" do
      stub_request(:get, 'https://www.googleapis.com/plus/v1/people/me').
        with(:headers => {'Authorization' => 'Bearer 12345'}).
        to_return(:status => 401, :body => JSON.dump(
          {"error" =>
            {"errors" =>
              [{"domain"       => "global",
                "reason"       => "authError",
                "message"      => "Invalid Credentials",
                "locationType" => "header",
                "location"     => "Authorization"}],
             "code"    => 401,
             "message" => "Invalid Credentials"}}))

      get :index, {}, valid_session
      session[:token].should be_nil
      session[:flash][:notice].should =~ /Your session has expired/
      response.should redirect_to(oauth2_authorize_url)
    end
  end

  describe "GET show" do
    it "assigns the requested quiz as @quiz" do
      quiz = Factory :quiz
      get :show, {:id => quiz.to_param}, valid_session
      assigns(:quiz).should eq(quiz)
    end
  end

  describe "GET new" do
    it "assigns a new quiz as @quiz" do
      get :new, {}, valid_session
      assigns(:quiz).should be_a_new(Quiz)
    end

    it "uses the US as the default country" do
      get :new, {}, valid_session
      assigns(:quiz).country_alpha2.should == 'US'
    end
  end

  describe "GET edit" do
    it "assigns the requested quiz as @quiz" do
      quiz = Factory :quiz
      get :edit, {:id => quiz.to_param}, valid_session
      assigns(:quiz).should eq(quiz)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Quiz" do
        expect {
          post :create, {:quiz => FactoryGirl.attributes_for(:quiz)}, valid_session
        }.to change(Quiz, :count).by(1)
      end

      it "assigns a newly created quiz as @quiz" do
        post :create, {:quiz => FactoryGirl.attributes_for(:quiz)}, valid_session
        assigns(:quiz).should be_a(Quiz)
        assigns(:quiz).should be_persisted
      end

      it "redirects to the edit form for the newly created quiz" do
        post :create, {:quiz => FactoryGirl.attributes_for(:quiz)}, valid_session
        response.should redirect_to(edit_quiz_url(Quiz.last))
      end

      it "uses the user's Google+ profile ID as the owner" do
        post :create, {:quiz => FactoryGirl.attributes_for(:quiz)}, valid_session
        Quiz.last.owner_id.should == '115478738847874567952'
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved quiz as @quiz" do
        # Trigger the behavior that occurs when invalid params are submitted
        Quiz.any_instance.stub(:save).and_return(false)
        post :create, {:quiz => {}}, valid_session
        assigns(:quiz).should be_a_new(Quiz)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Quiz.any_instance.stub(:save).and_return(false)
        post :create, {:quiz => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested quiz" do
        quiz = Factory :quiz
        # Assuming there are no other quizzes in the database, this
        # specifies that the Quiz created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Quiz.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => quiz.to_param, :quiz => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested quiz as @quiz" do
        quiz = Factory :quiz
        put :update, {:id => quiz.to_param, :quiz => FactoryGirl.attributes_for(:quiz)}, valid_session
        assigns(:quiz).should eq(quiz)
      end

      it "redirects to the quiz" do
        quiz = Factory :quiz
        put :update, {:id => quiz.to_param, :quiz => FactoryGirl.attributes_for(:quiz)}, valid_session
        response.should redirect_to(quiz)
      end
    end

    describe "with invalid params" do
      it "assigns the quiz as @quiz" do
        quiz = Factory :quiz
        # Trigger the behavior that occurs when invalid params are submitted
        Quiz.any_instance.stub(:save).and_return(false)
        put :update, {:id => quiz.to_param, :quiz => {}}, valid_session
        assigns(:quiz).should eq(quiz)
      end

      it "re-renders the 'edit' template" do
        quiz = Factory :quiz
        # Trigger the behavior that occurs when invalid params are submitted
        Quiz.any_instance.stub(:save).and_return(false)
        put :update, {:id => quiz.to_param, :quiz => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested quiz" do
      quiz = Factory :quiz
      expect {
        delete :destroy, {:id => quiz.to_param}, valid_session
      }.to change(Quiz, :count).by(-1)
    end

    it "redirects to the quizzes list" do
      quiz = Factory :quiz
      delete :destroy, {:id => quiz.to_param}, valid_session
      response.should redirect_to(quizzes_url)
    end
  end

  describe "GET video_search" do
    it "handles when Signet encounters an expired access token" do
      quiz = Factory :quiz

stub_request(:get, "https://gdata.youtube.com/feeds/api/videos?alt=jsonc&q=Pythagorean%20Theorem%20in%2060%20Seconds&v=2").
         with(:headers =>
          {'Authorization'=>'Bearer 12345',
            'X-Gdata-Key'=>'key=AI39si6Vq4EFTnQt7cL51Mn_eOWS_qHvOtMbrUuGMYDxyKwexi9Sq0wraBz0lh8n5h_oVOF65TJsbCElVn5zlfRyMW0M0tnNvg'}).
         to_return(:status => 200, :body => <<-END, :headers => {})
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}
  </style>
  <a href=//www.google.com/><img src=//www.google.com/images/errors/logo_sm.gif alt=Google></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/feed/api/videos</code> was not found on this server.  <ins>That’s all we know.</ins>
END

      get(:video_search,
          {:quiz_id => quiz.to_param, :q => 'Pythagorean Theorem in 60 Seconds'},
          valid_session)
      session[:token].should be_nil
      session[:flash][:notice].should =~ /Your session has expired/
      response.should redirect_to(oauth2_authorize_url)
    end
  end
end